# Generated by Django 6.0.1 on 2026-01-14 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='patient_bookings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='availability.availabilityslot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
